on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-test:
    uses: ./.github/workflows/lint_test.yml

  # release:
  #   needs: lint-test
  #   uses: ./.github/workflows/release.yml
  #   secrets: inherit

  deploy:
    needs: lint-test
    uses: ./.github/workflows/pages.yml
    secrets: inherit
